// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mission.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Example.Common.Network.Protobuf.Mission {

  /// <summary>Holder for reflection information generated from mission.proto</summary>
  public static partial class MissionReflection {

    #region Descriptor
    /// <summary>File descriptor for mission.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MissionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1taXNzaW9uLnByb3RvIjQKE01pc3Npb25MaXN0UmVzcG9uc2USHQoIbWlz",
            "c2lvbnMYASADKAsyCy5NaXNzaW9uRFRPInQKCk1pc3Npb25EVE8SCgoCaWQY",
            "ASABKAkSKgoIY2F0ZWdvcnkYAiABKA4yGC5NaXNzaW9uRFRPLkNhdGVnb3J5",
            "RW51bSIuCgxDYXRlZ29yeUVudW0SCQoFQkFTSUMQABIJCgVTUElDRRABEggK",
            "BE1FQVQQAiIvCg9NaXNzaW9uUmVzcG9uc2USHAoHbWlzc2lvbhgBIAEoCzIL",
            "Lk1pc3Npb25EVE9CVwoZY29tLmV4YW1wbGUuZGVtby5wcm90b2J1ZkIMTWlz",
            "c2lvblByb3RvqgIrQ29tLkV4YW1wbGUuQ29tbW9uLk5ldHdvcmsuUHJvdG9i",
            "dWYuTWlzc2lvbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Example.Common.Network.Protobuf.Mission.MissionListResponse), global::Com.Example.Common.Network.Protobuf.Mission.MissionListResponse.Parser, new[]{ "Missions" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO), global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Parser, new[]{ "Id", "Category" }, null, new[]{ typeof(global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Example.Common.Network.Protobuf.Mission.MissionResponse), global::Com.Example.Common.Network.Protobuf.Mission.MissionResponse.Parser, new[]{ "Mission" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MissionListResponse : pb::IMessage<MissionListResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MissionListResponse> _parser = new pb::MessageParser<MissionListResponse>(() => new MissionListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MissionListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Example.Common.Network.Protobuf.Mission.MissionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionListResponse(MissionListResponse other) : this() {
      missions_ = other.missions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionListResponse Clone() {
      return new MissionListResponse(this);
    }

    /// <summary>Field number for the "missions" field.</summary>
    public const int MissionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO> _repeated_missions_codec
        = pb::FieldCodec.ForMessage(10, global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Parser);
    private readonly pbc::RepeatedField<global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO> missions_ = new pbc::RepeatedField<global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO> Missions {
      get { return missions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MissionListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MissionListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!missions_.Equals(other.missions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= missions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      missions_.WriteTo(output, _repeated_missions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      missions_.WriteTo(ref output, _repeated_missions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += missions_.CalculateSize(_repeated_missions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MissionListResponse other) {
      if (other == null) {
        return;
      }
      missions_.Add(other.missions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            missions_.AddEntriesFrom(input, _repeated_missions_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            missions_.AddEntriesFrom(ref input, _repeated_missions_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MissionDTO : pb::IMessage<MissionDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MissionDTO> _parser = new pb::MessageParser<MissionDTO>(() => new MissionDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MissionDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Example.Common.Network.Protobuf.Mission.MissionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionDTO(MissionDTO other) : this() {
      id_ = other.id_;
      category_ = other.category_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionDTO Clone() {
      return new MissionDTO(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 2;
    private global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum category_ = global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum.Basic;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MissionDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MissionDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Category != other.Category) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Category != global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum.Basic) hash ^= Category.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Category != global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum.Basic) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Category);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Category != global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum.Basic) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Category);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Category != global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum.Basic) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MissionDTO other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Category != global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum.Basic) {
        Category = other.Category;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Category = (global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Category = (global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO.Types.CategoryEnum) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MissionDTO message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum CategoryEnum {
        [pbr::OriginalName("BASIC")] Basic = 0,
        [pbr::OriginalName("SPICE")] Spice = 1,
        [pbr::OriginalName("MEAT")] Meat = 2,
      }

    }
    #endregion

  }

  public sealed partial class MissionResponse : pb::IMessage<MissionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MissionResponse> _parser = new pb::MessageParser<MissionResponse>(() => new MissionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MissionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Example.Common.Network.Protobuf.Mission.MissionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionResponse(MissionResponse other) : this() {
      mission_ = other.mission_ != null ? other.mission_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MissionResponse Clone() {
      return new MissionResponse(this);
    }

    /// <summary>Field number for the "mission" field.</summary>
    public const int MissionFieldNumber = 1;
    private global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO mission_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO Mission {
      get { return mission_; }
      set {
        mission_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MissionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MissionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Mission, other.Mission)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (mission_ != null) hash ^= Mission.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (mission_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Mission);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (mission_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Mission);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mission_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mission);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MissionResponse other) {
      if (other == null) {
        return;
      }
      if (other.mission_ != null) {
        if (mission_ == null) {
          Mission = new global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO();
        }
        Mission.MergeFrom(other.Mission);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (mission_ == null) {
              Mission = new global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO();
            }
            input.ReadMessage(Mission);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (mission_ == null) {
              Mission = new global::Com.Example.Common.Network.Protobuf.Mission.MissionDTO();
            }
            input.ReadMessage(Mission);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
