// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: planetGrpcService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Example.Common.Network.Protobuf.Planet.Grpc {

  /// <summary>Holder for reflection information generated from planetGrpcService.proto</summary>
  public static partial class PlanetGrpcServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for planetGrpcService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlanetGrpcServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdwbGFuZXRHcnBjU2VydmljZS5wcm90bxoMcGxhbmV0LnByb3RvGhtnb29n",
            "bGUvcHJvdG9idWYvZW1wdHkucHJvdG8yjQIKEVBsYW5ldEdycGNTZXJ2aWNl",
            "EjwKB0ZpbmRBbGwSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFy5QbGFuZXRS",
            "ZXNlYXJjaFJlc3BvbnNlIgASNAoESW5pdBISLlBsYW5ldEluaXRSZXF1ZXN0",
            "GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgASRAoQUmVtb3ZlQWxsUGxhbmV0",
            "cxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5F",
            "bXB0eSIAEj4KDFJlbW92ZVBsYW5ldBIULlBsYW5ldFJlbW92ZVJlcXVlc3Qa",
            "Fi5nb29nbGUucHJvdG9idWYuRW1wdHkiAEJhChljb20uZXhhbXBsZS5kZW1v",
            "LnByb3RvYnVmQhJQbGFuZXRTZXJ2aWNlUHJvdG+qAi9Db20uRXhhbXBsZS5D",
            "b21tb24uTmV0d29yay5Qcm90b2J1Zi5QbGFuZXQuR3JwY2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Example.Common.Network.Protobuf.Planet.PlanetReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
