// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: planetGrpcService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Com.Example.Common.Network.Protobuf.Planet.Grpc {
  public static partial class PlanetGrpcService
  {
    static readonly string __ServiceName = "PlanetGrpcService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::Com.Example.Common.Network.Protobuf.Planet.PlanetResearchResponse> __Marshaller_PlanetResearchResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Com.Example.Common.Network.Protobuf.Planet.PlanetResearchResponse.Parser));
    static readonly grpc::Marshaller<global::Com.Example.Common.Network.Protobuf.Planet.PlanetInitRequest> __Marshaller_PlanetInitRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Com.Example.Common.Network.Protobuf.Planet.PlanetInitRequest.Parser));
    static readonly grpc::Marshaller<global::Com.Example.Common.Network.Protobuf.Planet.PlanetRemoveRequest> __Marshaller_PlanetRemoveRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Com.Example.Common.Network.Protobuf.Planet.PlanetRemoveRequest.Parser));

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Example.Common.Network.Protobuf.Planet.PlanetResearchResponse> __Method_FindAll = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Example.Common.Network.Protobuf.Planet.PlanetResearchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FindAll",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_PlanetResearchResponse);

    static readonly grpc::Method<global::Com.Example.Common.Network.Protobuf.Planet.PlanetInitRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Init = new grpc::Method<global::Com.Example.Common.Network.Protobuf.Planet.PlanetInitRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Init",
        __Marshaller_PlanetInitRequest,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveAllPlanets = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveAllPlanets",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Com.Example.Common.Network.Protobuf.Planet.PlanetRemoveRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemovePlanet = new grpc::Method<global::Com.Example.Common.Network.Protobuf.Planet.PlanetRemoveRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemovePlanet",
        __Marshaller_PlanetRemoveRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Example.Common.Network.Protobuf.Planet.Grpc.PlanetGrpcServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for PlanetGrpcService</summary>
    public partial class PlanetGrpcServiceClient : grpc::ClientBase<PlanetGrpcServiceClient>
    {
      /// <summary>Creates a new client for PlanetGrpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PlanetGrpcServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PlanetGrpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PlanetGrpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PlanetGrpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PlanetGrpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Com.Example.Common.Network.Protobuf.Planet.PlanetResearchResponse FindAll(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FindAll(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Com.Example.Common.Network.Protobuf.Planet.PlanetResearchResponse FindAll(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FindAll, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Common.Network.Protobuf.Planet.PlanetResearchResponse> FindAllAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FindAllAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Example.Common.Network.Protobuf.Planet.PlanetResearchResponse> FindAllAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FindAll, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Init(global::Com.Example.Common.Network.Protobuf.Planet.PlanetInitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Init(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Init(global::Com.Example.Common.Network.Protobuf.Planet.PlanetInitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Init, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InitAsync(global::Com.Example.Common.Network.Protobuf.Planet.PlanetInitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InitAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InitAsync(global::Com.Example.Common.Network.Protobuf.Planet.PlanetInitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Init, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveAllPlanets(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveAllPlanets(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveAllPlanets(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveAllPlanets, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveAllPlanetsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveAllPlanetsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveAllPlanetsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveAllPlanets, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty RemovePlanet(global::Com.Example.Common.Network.Protobuf.Planet.PlanetRemoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemovePlanet(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty RemovePlanet(global::Com.Example.Common.Network.Protobuf.Planet.PlanetRemoveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemovePlanet, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemovePlanetAsync(global::Com.Example.Common.Network.Protobuf.Planet.PlanetRemoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemovePlanetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemovePlanetAsync(global::Com.Example.Common.Network.Protobuf.Planet.PlanetRemoveRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemovePlanet, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PlanetGrpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PlanetGrpcServiceClient(configuration);
      }
    }

  }
}
#endregion
