// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: planetGrpcService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Example.Common.Network.Protobuf.Planet.Grpc {

  /// <summary>Holder for reflection information generated from planetGrpcService.proto</summary>
  public static partial class PlanetGrpcServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for planetGrpcService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlanetGrpcServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdwbGFuZXRHcnBjU2VydmljZS5wcm90bxoMcGxhbmV0LnByb3RvGhtnb29n",
            "bGUvcHJvdG9idWYvZW1wdHkucHJvdG8yiQIKDVBsYW5ldFNlcnZpY2USPAoH",
            "RmluZEFsbBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoXLlBsYW5ldFJlc2Vh",
            "cmNoUmVzcG9uc2UiABI0CgRJbml0EhIuUGxhbmV0SW5pdFJlcXVlc3QaFi5n",
            "b29nbGUucHJvdG9idWYuRW1wdHkiABJEChBSZW1vdmVBbGxQbGFuZXRzEhYu",
            "Z29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5",
            "IgASPgoMUmVtb3ZlUGxhbmV0EhQuUGxhbmV0UmVtb3ZlUmVxdWVzdBoWLmdv",
            "b2dsZS5wcm90b2J1Zi5FbXB0eSIAQmEKGWNvbS5leGFtcGxlLmRlbW8ucHJv",
            "dG9idWZCElBsYW5ldFNlcnZpY2VQcm90b6oCL0NvbS5FeGFtcGxlLkNvbW1v",
            "bi5OZXR3b3JrLlByb3RvYnVmLlBsYW5ldC5HcnBjYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Example.Common.Network.Protobuf.Planet.PlanetReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
