// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: recipeGrpcService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from recipeGrpcService.proto</summary>
public static partial class RecipeGrpcServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for recipeGrpcService.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RecipeGrpcServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdyZWNpcGVHcnBjU2VydmljZS5wcm90bxoMcmVjaXBlLnByb3RvGhtnb29n",
          "bGUvcHJvdG9idWYvZW1wdHkucHJvdG8yjQIKEVJlY2lwZUdycGNTZXJ2aWNl",
          "EjwKB0ZpbmRBbGwSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFy5SZWNpcGVS",
          "ZXNlYXJjaFJlc3BvbnNlIgASNAoESW5pdBISLlJlY2lwZUluaXRSZXF1ZXN0",
          "GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgASRAoQUmVtb3ZlQWxsUmVjaXBl",
          "cxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5F",
          "bXB0eSIAEj4KDFJlbW92ZVJlY2lwZRIULlJlY2lwZVJlbW92ZVJlcXVlc3Qa",
          "Fi5nb29nbGUucHJvdG9idWYuRW1wdHkiAEIvChljb20uZXhhbXBsZS5kZW1v",
          "LnByb3RvYnVmQhJSZWNpcGVTZXJ2aWNlUHJvdG9iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Com.Example.Demo.Protobuf.Recipe.RecipeReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, null));
  }
  #endregion

}

#endregion Designer generated code
