// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: recipeGrpcService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class RecipeGrpcService
{
  static readonly string __ServiceName = "RecipeGrpcService";

  static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> __Marshaller_RecipeResearchResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest> __Marshaller_RecipeInitRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest> __Marshaller_RecipeRemoveRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest.Parser.ParseFrom);

  static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> __Method_FindAll = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "FindAll",
      __Marshaller_google_protobuf_Empty,
      __Marshaller_RecipeResearchResponse);

  static readonly grpc::Method<global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Init = new grpc::Method<global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
      grpc::MethodType.Unary,
      __ServiceName,
      "Init",
      __Marshaller_RecipeInitRequest,
      __Marshaller_google_protobuf_Empty);

  static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveAllRecipes = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
      grpc::MethodType.Unary,
      __ServiceName,
      "RemoveAllRecipes",
      __Marshaller_google_protobuf_Empty,
      __Marshaller_google_protobuf_Empty);

  static readonly grpc::Method<global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveRecipe = new grpc::Method<global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
      grpc::MethodType.Unary,
      __ServiceName,
      "RemoveRecipe",
      __Marshaller_RecipeRemoveRequest,
      __Marshaller_google_protobuf_Empty);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::RecipeGrpcServiceReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of RecipeGrpcService</summary>
  [grpc::BindServiceMethod(typeof(RecipeGrpcService), "BindService")]
  public abstract partial class RecipeGrpcServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> FindAll(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Init(global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> RemoveAllRecipes(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> RemoveRecipe(global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for RecipeGrpcService</summary>
  public partial class RecipeGrpcServiceClient : grpc::ClientBase<RecipeGrpcServiceClient>
  {
    /// <summary>Creates a new client for RecipeGrpcService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public RecipeGrpcServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for RecipeGrpcService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public RecipeGrpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected RecipeGrpcServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected RecipeGrpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse FindAll(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return FindAll(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse FindAll(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_FindAll, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> FindAllAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return FindAllAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> FindAllAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_FindAll, null, options, request);
    }
    public virtual global::Google.Protobuf.WellKnownTypes.Empty Init(global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return Init(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Google.Protobuf.WellKnownTypes.Empty Init(global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_Init, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InitAsync(global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return InitAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InitAsync(global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_Init, null, options, request);
    }
    public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveAllRecipes(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RemoveAllRecipes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveAllRecipes(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_RemoveAllRecipes, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveAllRecipesAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RemoveAllRecipesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveAllRecipesAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_RemoveAllRecipes, null, options, request);
    }
    public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveRecipe(global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RemoveRecipe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveRecipe(global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_RemoveRecipe, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveRecipeAsync(global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RemoveRecipeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> RemoveRecipeAsync(global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_RemoveRecipe, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override RecipeGrpcServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new RecipeGrpcServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(RecipeGrpcServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_FindAll, serviceImpl.FindAll)
        .AddMethod(__Method_Init, serviceImpl.Init)
        .AddMethod(__Method_RemoveAllRecipes, serviceImpl.RemoveAllRecipes)
        .AddMethod(__Method_RemoveRecipe, serviceImpl.RemoveRecipe).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, RecipeGrpcServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_FindAll, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse>(serviceImpl.FindAll));
    serviceBinder.AddMethod(__Method_Init, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Com.Example.Demo.Protobuf.Recipe.RecipeInitRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Init));
    serviceBinder.AddMethod(__Method_RemoveAllRecipes, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.RemoveAllRecipes));
    serviceBinder.AddMethod(__Method_RemoveRecipe, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Com.Example.Demo.Protobuf.Recipe.RecipeRemoveRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.RemoveRecipe));
  }

}
#endregion
