// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rewardGrpcService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Example.Common.Network.Protobuf.Reward.Grpc {

  /// <summary>Holder for reflection information generated from rewardGrpcService.proto</summary>
  public static partial class RewardGrpcServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for rewardGrpcService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RewardGrpcServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdyZXdhcmRHcnBjU2VydmljZS5wcm90bxoMcmV3YXJkLnByb3RvMoEBCg1S",
            "ZXdhcmRTZXJ2aWNlEjMKEEdldFJld2FyZHNPbkdvYWwSDi5SZXdhcmRSZXF1",
            "ZXN0Gg8uUmV3YXJkUmVzcG9uc2USOwoYR2V0UmV3YXJkc09uTGV2ZWxDbGVh",
            "cmVkEg4uUmV3YXJkUmVxdWVzdBoPLlJld2FyZFJlc3BvbnNlQmEKGWNvbS5l",
            "eGFtcGxlLmRlbW8ucHJvdG9idWZCElJld2FyZFNlcnZpY2VQcm90b6oCL0Nv",
            "bS5FeGFtcGxlLkNvbW1vbi5OZXR3b3JrLlByb3RvYnVmLlJld2FyZC5HcnBj",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Example.Common.Network.Protobuf.Reward.RewardReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
