// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: socketGrpcService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from socketGrpcService.proto</summary>
public static partial class SocketGrpcServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for socketGrpcService.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SocketGrpcServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chdzb2NrZXRHcnBjU2VydmljZS5wcm90bxoMc29ja2V0LnByb3RvGhtnb29n",
          "bGUvcHJvdG9idWYvZW1wdHkucHJvdG8yYQoXU29ja2V0U2VydmVyR3JwY1Nl",
          "cnZpY2USRgoPQ29ubmVjdFRvU2VydmVyEhYuZ29vZ2xlLnByb3RvYnVmLkVt",
          "cHR5GhkuU29ja2V0Q29ubmVjdGlvblJlc3BvbnNlIgBCNQoZY29tLmV4YW1w",
          "bGUuZGVtby5wcm90b2J1ZkIYU29ja2V0U2VydmVySGFuZGxlclByb3RvYgZw",
          "cm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Com.Example.Demo.Protobuf.Socket.SocketReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, null));
  }
  #endregion

}

#endregion Designer generated code
