### Send POST init request for 5 recipes
POST http://localhost:8071/planets/init
Content-Type: application/json

{
  "amount": 5
}

###

POST http://localhost:8071/socket/push

###

POST http://localhost:8071/socket/close

#Content-Type: application/json
#
#{
#  "amount": 5
#}

### Send GET to retrieve all the recipes
GET http://localhost:8071/planets/find-all

###
