version: '3'
services:
  demo-db:
    environment:
      - POSTGRES_PASSWORD=mydb
      - POSTGRES_USER=demouser
    image: library/postgres:12.3
    network_mode: bridge
    container_name: demo-db
    expose:
      - 5454
    ports:
      - 5454:5432
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - demo-db-data:/var/lib/demo-db/data
  demo-socket-server:
    image: rabbitmq:3.8.9-management
    container_name: socket-server
    environment:
      - RABBITMQ_DEFAULT_USER=sose-admin
      - RABBITMQ_DEFAULT_PASS=sose-pwd
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./init-rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
  recipe-planner:
      image: demo/recipe-planner:latest
      container_name: recipe-planner
      network_mode: bridge
      expose:
        - 8071
      ports:
        - 8071:8071
      restart: unless-stopped
      depends_on:
        - demo-db
        - demo-socket-server
      links:
        - demo-db
volumes:
  demo-db-data: null
