spring:
  profiles:
    include:
      - local
  datasource:
    driver-class-name: org.postgresql.Driver
    username: demouser
    password: mydb
    url: jdbc:postgresql://localhost:5432/demo_db
  flyway:
    enabled: true
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
server:
  port: 8071

springdoc:
  api-docs:
    path: /demo-api
  packages-to-scan: com.example.demo.controller

demo:
  definition:
    base-package: com.example.demo.domain
  migration:
    default-output-folder: /src/main/resources/db/migration/
