spring:
  profiles:
    include:
      - local
  datasource:
    driver-class-name: org.postgresql.Driver
    username: demouser
    password: mydb
    url: jdbc:postgresql://localhost:5432/demo_db
  flyway:
    enabled: true
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: override-in-application-local
    password: override-in-application-local
server:
  port: 8071

grpc:
  server:
    port: 6565

springdoc:
  api-docs:
    path: /demo-api
  packages-to-scan: com.example.demo.controller
