spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  config:
    activate:
      on-profile: auto-generate-ddl
---
spring:
  config:
    activate:
      on-profile: no-security
---
spring:
  config:
    activate:
      on-profile: enable-rest