spring:
  profiles:
    include:
      - local
  datasource:
    driver-class-name: org.postgresql.Driver
    username: demouser
    password: mydb
    url: jdbc:postgresql://localhost:5432/demo_db
  flyway:
    enabled: true
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
server:
  port: 8071