// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: recipeService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class RecipeService
{
  static readonly string __ServiceName = "RecipeService";

  static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> __Marshaller_RecipeResearchResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse.Parser.ParseFrom);

  static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> __Method_FindAll = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "FindAll",
      __Marshaller_google_protobuf_Empty,
      __Marshaller_RecipeResearchResponse);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::RecipeServiceReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of RecipeService</summary>
  [grpc::BindServiceMethod(typeof(RecipeService), "BindService")]
  public abstract partial class RecipeServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> FindAll(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for RecipeService</summary>
  public partial class RecipeServiceClient : grpc::ClientBase<RecipeServiceClient>
  {
    /// <summary>Creates a new client for RecipeService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public RecipeServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for RecipeService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public RecipeServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected RecipeServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected RecipeServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse FindAll(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return FindAll(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse FindAll(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_FindAll, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> FindAllAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return FindAllAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse> FindAllAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_FindAll, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override RecipeServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new RecipeServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(RecipeServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_FindAll, serviceImpl.FindAll).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, RecipeServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_FindAll, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Com.Example.Demo.Protobuf.Recipe.RecipeResearchResponse>(serviceImpl.FindAll));
  }

}
#endregion
