// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: recipeService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from recipeService.proto</summary>
public static partial class RecipeServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for recipeService.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RecipeServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNyZWNpcGVTZXJ2aWNlLnByb3RvGgxyZWNpcGUucHJvdG8aG2dvb2dsZS9w",
          "cm90b2J1Zi9lbXB0eS5wcm90bzJNCg1SZWNpcGVTZXJ2aWNlEjwKB0ZpbmRB",
          "bGwSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFy5SZWNpcGVSZXNlYXJjaFJl",
          "c3BvbnNlIgBCLwoZY29tLmV4YW1wbGUuZGVtby5wcm90b2J1ZkISUmVjaXBl",
          "U2VydmljZVByb3RvYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Com.Example.Demo.Protobuf.Recipe.RecipeReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, null));
  }
  #endregion

}

#endregion Designer generated code
